fix path

diff --git a/aux/gcc b/aux/gcc
--- a/aux/gcc
+++ b/aux/gcc
@@ -5,8 +5,13 @@ dir=`dirname "$0"`
 if [ ! -z "$COMPILE_COMMAND_DB" ]; then
 	if [ ! -z "$KLLVM" ]; then
             ${KLLVM}/build/bin/clang "$@"
-	else
+        elif [ -f /home/acanino/llvm/build/bin/clang ]; then
 	    /home/acanino/llvm/build/bin/clang "$@"
+        elif [ -f /home/aspire/llvm/build/bin/clang ]; then
+	    /home/aspire/llvm/build/bin/clang "$@"
+	else
+	    echo "Compiler not found"
+	    exit 1
 	fi
 else
 	$dir/gcc-orig "$@"
diff --git a/aux/ld b/aux/ld
--- a/aux/ld
+++ b/aux/ld
@@ -4,6 +4,11 @@ dir=`dirname "$0"`
 
 if [ ! -z "$KLLVM" ]; then
     ${KLLVM}/build/bin/ld.lld "$@"
-else
+elif [ -f /home/acanino/llvm/build/bin/ld.lld ]; then
     /home/acanino/llvm/build/bin/ld.lld "$@"
+elif [ -f /home/aspire/llvm/build/bin/ld.lld ]; then
+    /home/aspire/llvm/build/bin/ld.lld "$@"
+else
+    echo "Loader not found"
+    exit 1
 fi
