fix aux ld

diff --git a/aux/ld b/aux/ld
--- a/aux/ld
+++ b/aux/ld
@@ -2,13 +2,18 @@
 
 dir=`dirname "$0"`
 
-if [ ! -z "$KLLVM" ]; then
-    ${KLLVM}/build/bin/ld.lld "$@"
-elif [ -f /home/acanino/llvm/build/bin/ld.lld ]; then
-    /home/acanino/llvm/build/bin/ld.lld "$@"
-elif [ -f /home/aspire/llvm/build/bin/ld.lld ]; then
-    /home/aspire/llvm/build/bin/ld.lld "$@"
+if [ ! -z "$COMPILE_COMMAND_DB" ]; then
+	if [ ! -z "$KLLVM" ]; then
+	    ${KLLVM}/build/bin/ld.lld "$@"
+	elif [ -f /home/acanino/llvm/build/bin/ld.lld ]; then
+	    /home/acanino/llvm/build/bin/ld.lld "$@"
+	elif [ -f /home/aspire/llvm/build/bin/ld.lld ]; then
+	    /home/aspire/llvm/build/bin/ld.lld "$@"
+	else
+	    echo "Loader not found"
+	    exit 1
+	fi
 else
-    echo "Loader not found"
-    exit 1
+	$dir/ld-orig "$@"
 fi
+exit
